source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BlurSpinner_Example', :exclusive => true do
  pod "BlurSpinner", :path => "../"
  pod 'FXBlurView', '~> 1.6'
end

target 'BlurSpinner_Tests', :exclusive => true do
  pod "BlurSpinner", :path => "../"
  
  pod 'FXBlurView', '~> 1.6'
end
